use_frameworks!

target 'LastFMSwift_Example' do
  
  pod 'LastFMSwift', :path => '../'

  target 'LastFMSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
